### ISSUE TITLE
CPU Healthcheck is broken

### ISSUE THREAD

**Issue by rohitthakur2590** [ansible-network/network.healthchecks#5]
### Description
CPU Healthcheck is broken  with the following observation
-  There are hardcoded values getting returned for the threshold
- Sucess scenario also returns random hardcoded data.
- Failure scenario doesn't work
### Playbook

```yaml
- name: Run Network Healthchecks
  hosts: network
  tasks:
    - name: Run CPU healthchecks
      ansible.builtin.include_role:
        name: network.healthchecks.cpu
      vars:
        cpu_utilization:
          details: true
          warning_threshold: 0
          critical_threshold: 0
      register: cpu_result

```

### Actual  Output
```text
TASK [network.healthchecks.cpu : CPU health checks] ****************************
task path: /usr/share/ansible/collections/ansible_collectionsetwork/healthchecks/roles/cpu/tasks/main.yml:27
[WARNING]: Collection ansible.netcommon does not support Ansible version
2.15.10
[WARNING]: Collection cisco.ios does not support Ansible version 2.15.10
redirecting (type: become) ansible.builtin.enable to ansible.netcommon.enable
ok: [rtr1] => {
    "failed_when_result": false,
    "health_checks": {
        "cpu_utilization": {
            "1_min_avg": 0,
            "5_min_avg": 0,
            "message": "CPU utilization is within acceptable limits",
            "status": "PASS",
            "threshold": 90
        },
        "result": "PASS"
    }
}
PLAY RECAP *********************************************************************
rtr1                       : ok=9    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0
```
